ShouldRemoveFileByIdAsync -> FAIL
hassanhabib/Standard.AI.OpenAI pull request #395
Opened 2023-06-20 17:19 UTC by sulton-max

Closes #394

2023-06-21 06:07 UTC, hassanhabib commented on Standard.AI.OpenAI.Tests.Unit/Services/Orchestrations/AIFiles/AIFileOrchestrationServiceTests.Exceptions.RemoveFileById.cs
> +        )
Move this `)` next to the variable name

2023-06-21 06:07 UTC, hassanhabib commented on Standard.AI.OpenAI.Tests.Unit/Services/Orchestrations/AIFiles/AIFileOrchestrationServiceTests.Exceptions.RemoveFileById.cs
> +        public async Task ShouldThrowDependencyExceptionOnRemoveFileIfDependencyExceptionErrorOccursAsync(Xeption dependencyException)
Is this line over 120 characters?

2023-06-21 06:08 UTC, hassanhabib commented on Standard.AI.OpenAI.Tests.Unit/Services/Orchestrations/AIFiles/AIFileOrchestrationServiceTests.Validation.RemoveFileByIdAsync.cs
> +        var invalidFileId = default(string);
Please refer to other tests as to how we generate random invalid string values.

2023-06-21 06:08 UTC, hassanhabib commented on Standard.AI.OpenAI.Tests.Unit/Services/Orchestrations/AIFiles/AIFileOrchestrationServiceTests.cs
> +            return actualFileId => actualFileId.Equals(fileId);
One liners should be fat-arrowed - refer to The C# Standard

2023-06-21 06:09 UTC, hassanhabib commented on Standard.AI.OpenAI.Tests.Unit/Services/Orchestrations/AIFiles/AIFileOrchestrationServiceTests.cs
> +            return randomId;
`return` statements should have their own line refer to The C# Standard

2023-06-21 09:21 UTC, sulton-max commented on Standard.AI.OpenAI.Tests.Unit/Services/Orchestrations/AIFiles/AIFileOrchestrationServiceTests.Validation.RemoveFileByIdAsync.cs
> +        var invalidFileId = default(string);
Should I use null value with inline data ? ( referring to validation test of that same method on foundation service ), because I thought it makes sense for orchestration service to validate only if parameter is not null

2023-06-24 17:07 UTC, ElbekDeveloper requested changes

2023-06-24 17:07 UTC, ElbekDeveloper commented on Standard.AI.OpenAI/Services/Orchestrations/AIFiles/AIFileOrchestrationService.cs
> +            return aiFile;
Empty line before `return`

2023-06-25 12:16 UTC, hassanhabib commented on Standard.AI.OpenAI.Tests.Unit/Services/Orchestrations/AIFiles/AIFileOrchestrationServiceTests.Logic.RemoveFileByIdAsync.cs
> +            AIFile actualAIFile = await this.aiFileOrchestrationService.RemoveFileByIdAsync(inputFileId);
Break this line from `await ...` to the next line with one tab

2023-06-25 22:02 UTC, merged